/**
 * Art Library of Alpha Org
 * This is a server for Art Library of Alpha Org. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nnworkspace@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ArtworkStatus = 'available' | 'reserved' | 'in use' | 'return reported';

export const ArtworkStatus = {
    Available: 'available' as ArtworkStatus,
    Reserved: 'reserved' as ArtworkStatus,
    InUse: 'in use' as ArtworkStatus,
    ReturnReported: 'return reported' as ArtworkStatus
};

