/**
 * Art Library of Alpha Org
 * This is a server for Art Library of Alpha Org.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nnworkspace@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LendingAllOf } from './lendingAllOf';
import { NewLending } from './newLending';


export interface Lending {
    /**
     * ID of a artwork. ID of an artwork is a combination of the artist name and the artwork name and optional integer identifier
     */
    id: string;
    self: string;
    /**
     * ID of a artwork. ID of an artwork is a combination of the artist name and the artwork name and optional integer identifier
     */
    artworkId: string;
    /**
     * ID of the user who borrowed the artwork.
     */
    userId: string;
    lendingStatus: Lending.LendingStatusEnum;
    startDate: Date;
    endDate: Date;
    /**
     * Date and time when this record is created.
     */
    createdOn: string;
    /**
     * User id of the borrower who created this record.
     */
    createdBy: string;
    /**
     * Time of last update of this record, a timestamp.
     */
    lastUpdatedOn: string;
    /**
     * User id of the admin who last updated this record.
     */
    lastUpdatedBy: string;
    /**
     * Date when the artwork is sent to the lender.
     */
    artworkSentOn?: string | null;
    /**
     * User id of the admin who sent the artwork to the lender
     */
    artworkSentBy?: string | null;
    /**
     * Date when the artwork is restored to the art library.
     */
    artworkRestoredOn?: string | null;
    /**
     * User id of the admin who restored the artwork to its storage location in the library, after a user has returned it.
     */
    artworkRestoredBy?: string | null;
}
export namespace Lending {
    export type LendingStatusEnum = 'reserved' | 'sent to lender' | 'return reported' | 'lending closed' | 'record deleted';
    export const LendingStatusEnum = {
        Reserved: 'reserved' as LendingStatusEnum,
        SentToLender: 'sent to lender' as LendingStatusEnum,
        ReturnReported: 'return reported' as LendingStatusEnum,
        LendingClosed: 'lending closed' as LendingStatusEnum,
        RecordDeleted: 'record deleted' as LendingStatusEnum
    };
}


