/**
 * Art Library of Alpha Org
 * This is a server for Art Library of Alpha Org. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nnworkspace@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ArtForm = 'painting' | 'photograph' | 'print' | 'sculpture' | 'assemblage' | 'collage';

export const ArtForm = {
    Painting: 'painting' as ArtForm,
    Photograph: 'photograph' as ArtForm,
    Print: 'print' as ArtForm,
    Sculpture: 'sculpture' as ArtForm,
    Assemblage: 'assemblage' as ArtForm,
    Collage: 'collage' as ArtForm
};

