/**
 * Art Library of Alpha Org
 * This is a server for Art Library of Alpha Org. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nnworkspace@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NewArtwork { 
    name: string;
    artForm: NewArtwork.ArtFormEnum;
    description?: string;
    storageLocation: string;
    artist?: string;
    /**
     * If the artwork is a print or other manufactured article, record the publisher or manufacturer here.
     */
    producer?: string;
    /**
     * If the artwork has a serial number, record it in this property.
     */
    productSerialNumber?: string;
    imageUrls?: Array<string>;
    /**
     * The date when Alpha Org obtained this piece of artwork.
     */
    dateObtained?: string;
    /**
     * Market value of this piece of artwork. Unit in Euro.
     */
    marketValue?: number;
}
export namespace NewArtwork {
    export type ArtFormEnum = 'painting' | 'photograph' | 'print' | 'sculpture' | 'assemblage' | 'collage';
    export const ArtFormEnum = {
        Painting: 'painting' as ArtFormEnum,
        Photograph: 'photograph' as ArtFormEnum,
        Print: 'print' as ArtFormEnum,
        Sculpture: 'sculpture' as ArtFormEnum,
        Assemblage: 'assemblage' as ArtFormEnum,
        Collage: 'collage' as ArtFormEnum
    };
}


